version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    image: postgres:13
    environment:
      - POSTGRES_DB=testing_e2e
      - POSTGRES_USER=e2e_user
      - POSTGRES_PASSWORD=e2e_pass123
    ports:
      - 5435:5432

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 5050:80
